-- Partition trade runtime persistence by tenant while keeping backward compatibility.
ALTER TABLE "TradeRuntimeState"
ADD COLUMN "tenantId" TEXT;

UPDATE "TradeRuntimeState"
SET "tenantId" = 'default'
WHERE "tenantId" IS NULL OR btrim("tenantId") = '';

ALTER TABLE "TradeRuntimeState"
ALTER COLUMN "tenantId" SET NOT NULL;

DO $$
BEGIN
  BEGIN
    ALTER TABLE "TradeRuntimeState"
    ALTER COLUMN "id" ADD GENERATED BY DEFAULT AS IDENTITY;
  EXCEPTION
    WHEN duplicate_object THEN NULL;
  END;
END $$;

CREATE UNIQUE INDEX "TradeRuntimeState_tenantId_key"
ON "TradeRuntimeState"("tenantId");
