INSERT INTO "RuntimeSetting" ("key", "value", "updatedAt") VALUES
  ('LIQUIDITY_HUNT_DYNAMIC_TP_BUFFER_PCT', '0.15', NOW()),
  ('LIQUIDITY_HUNT_TRAILING_STOP_ENABLED', 'true', NOW()),
  ('LIQUIDITY_HUNT_TRAILING_ACTIVATION_PNL_PCT', '5', NOW()),
  ('LIQUIDITY_HUNT_TRAILING_GAP_PNL_PCT', '2', NOW()),
  ('LIQUIDITY_HUNT_BREAK_EVEN_TRIGGER_PNL_PCT', '5', NOW()),
  ('LIQUIDITY_HUNT_COST_BUFFER_PCT', '1.5', NOW()),
  ('LIQUIDITY_HUNT_MIN_NET_TP_PCT', '8', NOW())
ON CONFLICT ("key") DO UPDATE
SET "value" = EXCLUDED."value",
    "updatedAt" = NOW();
