INSERT INTO "RuntimeSetting" ("key", "value", "updatedAt") VALUES
  ('VIOLENT_MOVE_ALERT_ENABLED', 'true', NOW()),
  ('VIOLENT_MOVE_MIN_VOLATILITY_PCT', '5', NOW()),
  ('VIOLENT_MOVE_MIN_VOLATILITY_PERCENTILE', '85', NOW()),
  ('VIOLENT_MOVE_MIN_VOLUME_MULTIPLIER', '2', NOW()),
  ('VIOLENT_MOVE_STOCH_MIN_K', '55', NOW()),
  ('VIOLENT_MOVE_DROP_CAUTION_ENABLED', 'true', NOW()),
  ('VIOLENT_MOVE_DROP_WINDOW_MINUTES', '90', NOW()),
  ('VIOLENT_MOVE_DROP_RATIO', '0.55', NOW()),
  ('VIOLENT_MOVE_DROP_ABS_VOLATILITY_PCT', '2.2', NOW()),
  ('VIOLENT_MOVE_DROP_REQUIRE_STOCH_ROLLOVER', 'true', NOW())
ON CONFLICT ("key") DO UPDATE
SET
  "value" = EXCLUDED."value",
  "updatedAt" = NOW();
