export type TokenCategory =
  | "AI"
  | "DEFI"
  | "GAMING"
  | "LAYER1"
  | "LAYER2"
  | "MEME"
  | "RWA"
  | "STOCK"
  | "OTHER";

export type TokenMeta = {
  name: string;
  category: TokenCategory;
};

export const TOKEN_METADATA: Readonly<Record<string, TokenMeta>> = {
  // ── Layer 1 ──────────────────────────────────────────────────────────
  BTC:      { name: "Bitcoin",              category: "LAYER1" },
  ETH:      { name: "Ethereum",             category: "LAYER1" },
  SOL:      { name: "Solana",               category: "LAYER1" },
  BNB:      { name: "BNB",                  category: "LAYER1" },
  XRP:      { name: "XRP",                  category: "LAYER1" },
  ADA:      { name: "Cardano",              category: "LAYER1" },
  AVAX:     { name: "Avalanche",            category: "LAYER1" },
  SUI:      { name: "Sui",                  category: "LAYER1" },
  APT:      { name: "Aptos",                category: "LAYER1" },
  ATOM:     { name: "Cosmos",               category: "LAYER1" },
  TON:      { name: "Toncoin",              category: "LAYER1" },
  NEAR:     { name: "NEAR Protocol",        category: "LAYER1" },
  TRX:      { name: "TRON",                 category: "LAYER1" },
  DOT:      { name: "Polkadot",             category: "LAYER1" },
  ICP:      { name: "Internet Computer",    category: "LAYER1" },
  FIL:      { name: "Filecoin",             category: "LAYER1" },
  HBAR:     { name: "Hedera",               category: "LAYER1" },
  XLM:      { name: "Stellar",              category: "LAYER1" },
  ALGO:     { name: "Algorand",             category: "LAYER1" },
  XMR:      { name: "Monero",               category: "LAYER1" },
  ZEC:      { name: "Zcash",                category: "LAYER1" },
  DASH:     { name: "Dash",                 category: "LAYER1" },
  BCH:      { name: "Bitcoin Cash",         category: "LAYER1" },
  LTC:      { name: "Litecoin",             category: "LAYER1" },
  ETC:      { name: "Ethereum Classic",     category: "LAYER1" },
  BSV:      { name: "Bitcoin SV",           category: "LAYER1" },
  SEI:      { name: "Sei",                  category: "LAYER1" },
  MINA:     { name: "Mina Protocol",        category: "LAYER1" },
  IOTA:     { name: "IOTA",                 category: "LAYER1" },
  CFX:      { name: "Conflux",              category: "LAYER1" },
  CELO:     { name: "Celo",                 category: "LAYER1" },
  NEO:      { name: "Neo",                  category: "LAYER1" },
  GAS:      { name: "Neo Gas",              category: "LAYER1" },
  INJ:      { name: "Injective",            category: "LAYER1" },
  KAS:      { name: "Kaspa",                category: "LAYER1" },
  MON:      { name: "Monad",                category: "LAYER1" },
  MOVE:     { name: "Movement Network",     category: "LAYER1" },
  S:        { name: "Sonic",                category: "LAYER1" },
  BERA:     { name: "Berachain",            category: "LAYER1" },
  INIT:     { name: "Initia",               category: "LAYER1" },
  ZETA:     { name: "ZetaChain",            category: "LAYER1" },
  IP:       { name: "Story Protocol",       category: "LAYER1" },
  AR:       { name: "Arweave",              category: "LAYER1" },
  ARK:      { name: "Ark Network",          category: "LAYER1" },
  ORDI:     { name: "Ordinals",             category: "LAYER1" },
  ONE:      { name: "Harmony",              category: "LAYER1" },
  KAVA:     { name: "Kava",                 category: "LAYER1" },
  VIC:      { name: "Viction",              category: "LAYER1" },
  ROSE:     { name: "Oasis Network",        category: "LAYER1" },
  // ── Layer 2 ──────────────────────────────────────────────────────────
  ARB:      { name: "Arbitrum",             category: "LAYER2" },
  OP:       { name: "Optimism",             category: "LAYER2" },
  POL:      { name: "Polygon",              category: "LAYER2" },
  MATIC:    { name: "Polygon",              category: "LAYER2" },
  STRK:     { name: "Starknet",             category: "LAYER2" },
  ZK:       { name: "ZKsync",               category: "LAYER2" },
  ZKS:      { name: "ZKspace",              category: "LAYER2" },
  METIS:    { name: "Metis",                category: "LAYER2" },
  MANTA:    { name: "Manta Network",        category: "LAYER2" },
  ZEN:      { name: "Horizen",              category: "LAYER2" },
  BLAST:    { name: "Blast",                category: "LAYER2" },
  HEMI:     { name: "Hemi",                 category: "LAYER2" },
  MEGA:     { name: "MegaETH",              category: "LAYER2" },
  MNT:      { name: "Mantle",               category: "LAYER2" },
  DYM:      { name: "Dymension",            category: "LAYER2" },
  ALT:      { name: "AltLayer",             category: "LAYER2" },
  SAGA:     { name: "Saga Protocol",        category: "LAYER2" },
  SCR:      { name: "Scroll",               category: "LAYER2" },
  LINEA:    { name: "Linea",                category: "LAYER2" },
  AZTEC:    { name: "Aztec Network",        category: "LAYER2" },
  STX:      { name: "Stacks",               category: "LAYER2" },
  MERL:     { name: "Merlin Chain",         category: "LAYER2" },
  TIA:      { name: "Celestia",             category: "LAYER2" },
  LAYER:    { name: "Layer3",               category: "LAYER2" },
  // ── DeFi ─────────────────────────────────────────────────────────────
  AAVE:     { name: "Aave",                 category: "DEFI" },
  UNI:      { name: "Uniswap",              category: "DEFI" },
  LINK:     { name: "Chainlink",            category: "DEFI" },
  MKR:      { name: "Maker",                category: "DEFI" },
  CRV:      { name: "Curve DAO",            category: "DEFI" },
  LDO:      { name: "Lido DAO",             category: "DEFI" },
  MORPHO:   { name: "Morpho",               category: "DEFI" },
  ENA:      { name: "Ethena",               category: "DEFI" },
  PENDLE:   { name: "Pendle",               category: "DEFI" },
  COMP:     { name: "Compound",             category: "DEFI" },
  SNX:      { name: "Synthetix",            category: "DEFI" },
  GMX:      { name: "GMX",                  category: "DEFI" },
  DYDX:     { name: "dYdX",                 category: "DEFI" },
  JUP:      { name: "Jupiter",              category: "DEFI" },
  HYPE:     { name: "Hyperliquid",          category: "DEFI" },
  APEX:     { name: "ApeX Protocol",        category: "DEFI" },
  UMA:      { name: "UMA",                  category: "DEFI" },
  MAV:      { name: "Maverick Protocol",    category: "DEFI" },
  RESOLV:   { name: "Resolv",               category: "DEFI" },
  SYRUP:    { name: "Maple Finance",        category: "DEFI" },
  SUSHI:    { name: "SushiSwap",            category: "DEFI" },
  CAKE:     { name: "PancakeSwap",          category: "DEFI" },
  AERO:     { name: "Aerodrome",            category: "DEFI" },
  RUNE:     { name: "THORchain",            category: "DEFI" },
  SKY:      { name: "Sky (Maker)",          category: "DEFI" },
  ZRO:      { name: "LayerZero",            category: "DEFI" },
  EIGEN:    { name: "EigenLayer",           category: "DEFI" },
  ETHFI:    { name: "ether.fi",             category: "DEFI" },
  JTO:      { name: "Jito",                 category: "DEFI" },
  REZ:      { name: "Renzo",                category: "DEFI" },
  PYTH:     { name: "Pyth Network",         category: "DEFI" },
  TRB:      { name: "Tellor",               category: "DEFI" },
  BANANA:   { name: "Banana Gun",           category: "DEFI" },
  ENS:      { name: "Ethereum Name Service", category: "DEFI" },
  W:        { name: "Wormhole",             category: "DEFI" },
  USUAL:    { name: "Usual Protocol",       category: "DEFI" },
  VVV:      { name: "Venice Finance",       category: "DEFI" },
  BIO:      { name: "Bio Protocol",         category: "DEFI" },
  WLFI:     { name: "World Liberty",        category: "DEFI" },
  ZORA:     { name: "Zora",                 category: "DEFI" },
  STBL:     { name: "Stable Jack",          category: "DEFI" },
  STABLE:   { name: "Stable Asset",         category: "DEFI" },
  WCT:      { name: "WalletConnect",        category: "DEFI" },
  FTT:      { name: "FTX Token",            category: "DEFI" },
  // ── AI ───────────────────────────────────────────────────────────────
  FET:      { name: "Fetch.ai",             category: "AI" },
  RENDER:   { name: "Render",               category: "AI" },
  TAO:      { name: "Bittensor",            category: "AI" },
  WLD:      { name: "Worldcoin",            category: "AI" },
  ARKM:     { name: "Arkham",               category: "AI" },
  AI16Z:    { name: "ai16z",                category: "AI" },
  VIRTUAL:  { name: "Virtuals Protocol",    category: "AI" },
  KAITO:    { name: "Kaito",                category: "AI" },
  AIXBT:    { name: "AIXBT by Virtuals",    category: "AI" },
  IO:       { name: "io.net",               category: "AI" },
  GOAT:     { name: "Goatseus Maximus",     category: "AI" },
  GRASS:    { name: "Grass",                category: "AI" },
  GRIFFAIN: { name: "Griffain",             category: "AI" },
  ZEREBRO:  { name: "Zerebro",              category: "AI" },
  NIL:      { name: "Nillion",              category: "AI" },
  PROMPT:   { name: "PromptFi",             category: "AI" },
  HYPER:    { name: "HyperAI",              category: "AI" },
  LIT:      { name: "Lit Protocol",         category: "AI" },
  SOPH:     { name: "Sophon",               category: "AI" },
  "0G":     { name: "0G Network",           category: "AI" },
  PROVE:    { name: "Prove",                category: "AI" },
  ANIME:    { name: "Animecoin",            category: "AI" },
  // ── Gaming ───────────────────────────────────────────────────────────
  IMX:      { name: "Immutable",            category: "GAMING" },
  GALA:     { name: "Gala",                 category: "GAMING" },
  AXS:      { name: "Axie Infinity",        category: "GAMING" },
  SAND:     { name: "The Sandbox",          category: "GAMING" },
  MANA:     { name: "Decentraland",         category: "GAMING" },
  BEAM:     { name: "Beam",                 category: "GAMING" },
  BIGTIME:  { name: "Big Time",             category: "GAMING" },
  MAVIA:    { name: "Heroes of Mavia",      category: "GAMING" },
  ACE:      { name: "Fusionist",            category: "GAMING" },
  APE:      { name: "ApeCoin",              category: "GAMING" },
  BLUR:     { name: "Blur",                 category: "GAMING" },
  ME:       { name: "Magic Eden",           category: "GAMING" },
  PENGU:    { name: "Pudgy Penguins",       category: "GAMING" },
  DOOD:     { name: "Doodles",              category: "GAMING" },
  TNSR:     { name: "Tensor",               category: "GAMING" },
  XAI:      { name: "Xai",                  category: "GAMING" },
  YGG:      { name: "Yield Guild Games",    category: "GAMING" },
  SUPER:    { name: "SuperVerse",           category: "GAMING" },
  GMT:      { name: "STEPN",                category: "GAMING" },
  HMSTR:    { name: "Hamster Kombat",       category: "GAMING" },
  PIXEL:    { name: "Pixels",               category: "GAMING" },
  // ── RWA ──────────────────────────────────────────────────────────────
  ONDO:     { name: "Ondo Finance",         category: "RWA" },
  POLYX:    { name: "Polymesh",             category: "RWA" },
  PAXG:     { name: "PAX Gold",             category: "RWA" },
  RSR:      { name: "Reserve Rights",       category: "RWA" },
  RIO:      { name: "Realio Network",       category: "RWA" },
  // ── Meme ─────────────────────────────────────────────────────────────
  DOGE:     { name: "Dogecoin",             category: "MEME" },
  SHIB:     { name: "Shiba Inu",            category: "MEME" },
  PEPE:     { name: "Pepe",                 category: "MEME" },
  BONK:     { name: "Bonk",                 category: "MEME" },
  FLOKI:    { name: "Floki",                category: "MEME" },
  WIF:      { name: "dogwifhat",            category: "MEME" },
  FARTCOIN: { name: "Fartcoin",             category: "MEME" },
  MEME:     { name: "Memecoin",             category: "MEME" },
  POPCAT:   { name: "Popcat",               category: "MEME" },
  MOODENG:  { name: "Moo Deng",             category: "MEME" },
  BRETT:    { name: "Brett",                category: "MEME" },
  PURR:     { name: "Purr",                 category: "MEME" },
  MEW:      { name: "cat in a dogs world",  category: "MEME" },
  TURBO:    { name: "Turbo",                category: "MEME" },
  NEIRO:    { name: "Neiro",                category: "MEME" },
  MELANIA:  { name: "Melania Meme",         category: "MEME" },
  TRUMP:    { name: "TRUMP",                category: "MEME" },
  VINE:     { name: "Vine Coin",            category: "MEME" },
  PNUT:     { name: "Peanut the Squirrel",  category: "MEME" },
  NOT:      { name: "Notcoin",              category: "MEME" },
  BOME:     { name: "Book of Meme",         category: "MEME" },
  SPX:      { name: "SPX6900",              category: "MEME" },
  PEOPLE:   { name: "ConstitutionDAO",      category: "MEME" },
  CHILLGUY: { name: "Chill Guy",            category: "MEME" },
  BABY:     { name: "BabyDoge",             category: "MEME" },
  PUMP:     { name: "Pump",                 category: "MEME" },
  TST:      { name: "Test Token",           category: "MEME" },
  USTC:     { name: "Terra Classic USD",    category: "MEME" },
  YZY:      { name: "YEEZY",               category: "MEME" },
  CHIP:     { name: "Chip",                 category: "MEME" },
  CC:       { name: "CC",                   category: "MEME" },
  SKR:      { name: "Skirmish",             category: "MEME" },
  // ── Stock Perps ───────────────────────────────────────────────────────
  TSLA:     { name: "Tesla",                category: "STOCK" },
  NVDA:     { name: "NVIDIA",               category: "STOCK" },
  AAPL:     { name: "Apple",                category: "STOCK" },
  AMZN:     { name: "Amazon",               category: "STOCK" },
  MSFT:     { name: "Microsoft",            category: "STOCK" },
  GOOG:     { name: "Alphabet",             category: "STOCK" },
  GOOGL:    { name: "Alphabet (Class A)",   category: "STOCK" },
  META:     { name: "Meta Platforms",       category: "STOCK" },
  NFLX:     { name: "Netflix",              category: "STOCK" },
  COIN:     { name: "Coinbase",             category: "STOCK" },
  BABA:     { name: "Alibaba",              category: "STOCK" },
  AMD:      { name: "AMD",                  category: "STOCK" },
  INTC:     { name: "Intel",                category: "STOCK" },
  PYPL:     { name: "PayPal",               category: "STOCK" },
  MSTR:     { name: "MicroStrategy",        category: "STOCK" },
  NIO:      { name: "NIO",                  category: "STOCK" },
  PLTR:     { name: "Palantir",             category: "STOCK" },
  SOFI:     { name: "SoFi Technologies",    category: "STOCK" },
  HOOD:     { name: "Robinhood",            category: "STOCK" },
  UBER:     { name: "Uber",                 category: "STOCK" },
  ABNB:     { name: "Airbnb",               category: "STOCK" },
  SHOP:     { name: "Shopify",              category: "STOCK" },
  SQ:       { name: "Block (Square)",       category: "STOCK" },
  SPOT:     { name: "Spotify",              category: "STOCK" },
  RBLX:     { name: "Roblox",               category: "STOCK" },
  // ── Other ─────────────────────────────────────────────────────────────
  MEMEFI:   { name: "MemeFi",               category: "OTHER" },
  ACT:      { name: "ACT",                  category: "OTHER" },
  "2Z":     { name: "2Z",                   category: "OTHER" },
  AVNT:     { name: "Avantis",              category: "OTHER" },
  ASTER:    { name: "Aster",                category: "OTHER" },
  FOGO:     { name: "Fogo",                 category: "OTHER" },
  MET:      { name: "Metaverse Token",      category: "OTHER" },
  NXPC:     { name: "NXPC",                 category: "OTHER" },
  XPL:      { name: "XPL",                  category: "OTHER" },
};
function normalizeBase(symbol: string): string {
  return symbol.trim().toUpperCase()
    .replace(/-PERP$/i, "")
    .replace(/-USDT-SWAP$/i, "")
    .replace(/-USDT$/i, "")
    .replace(/-PERP-USDT$/i, "");
}

export function getTokenName(symbol: string): string {
  const base = normalizeBase(symbol);
  return TOKEN_METADATA[base]?.name ?? base;
}

export function getTokenCategory(symbol: string): TokenCategory {
  const base = normalizeBase(symbol);
  return TOKEN_METADATA[base]?.category ?? "OTHER";
}

export function formatTokenDisplay(symbol: string): string {
  const base = normalizeBase(symbol);
  const meta = TOKEN_METADATA[base];
  return meta ? `${base} · ${meta.name}` : base;
}
