-- AlterTable
ALTER TABLE "WeeklyCapToken" ADD COLUMN     "stoch15mCrossUp" BOOLEAN NOT NULL DEFAULT false,
ADD COLUMN     "stoch15mD" DOUBLE PRECISION,
ADD COLUMN     "stoch15mK" DOUBLE PRECISION,
ADD COLUMN     "stoch1hCrossUp" BOOLEAN NOT NULL DEFAULT false,
ADD COLUMN     "stoch1hD" DOUBLE PRECISION,
ADD COLUMN     "stoch1hK" DOUBLE PRECISION,
ADD COLUMN     "stoch4hCrossUp" BOOLEAN NOT NULL DEFAULT false,
ADD COLUMN     "stoch4hD" DOUBLE PRECISION,
ADD COLUMN     "stoch4hK" DOUBLE PRECISION,
ADD COLUMN     "timeframeCrossCount" INTEGER NOT NULL DEFAULT 0;
